development:
  adapter: postgresql
  encoding: unicode
  database: r2013-03-19-photo-albm_development
  pool: 5
  host: localhost
  username: AdiSingh
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: r2013-03-19-photo-albm_test
  pool: 5
  host: localhost
  username: AdiSingh
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: r2013-03-19-photo-albm_production
  pool: 5
  host: localhost
  username: AdiSingh
  password:
